import { Customer } from "./customer.model";

export const CUSTOMERS: Customer[] = [
  {
    id: 1,
    email: "john.doe@example.com",
    name: "John",
    surname: "Doe",
    phone: "+1-555-555-1234",
    ethnicity: "Caucasian",
    tc_no: '12345678901',
    work_field: "Engineering",
    birthday: "1990-01-15",
    passport_no: "A12345678",
    passport_type: "Regular",
      schengen_status: 'Valid',
      company_info: 'ABC Engineering Ltd.',
      passport_start_date: '2020-06-01',
      passport_end_date: '2030-06-01',
      visa_end_date: '2025-05-01',
      passport_jpg_url: 'https://example.com/passports/john_doe.jpg',
      backup_1: 'None',
      backup_2: 'None',
    },
    {
      id: 2,
      email: 'jane.smith@example.com',
      name: 'Jane',
      surname: 'Smith',
      phone: '+44-777-555-9876',
      ethnicity: 'Asian',
      tc_no: '98765432101',
      work_field: 'Marketing',
      birthday: '1985-08-22',
      passport_no: 'B98765432',
      passport_type: 'Regular',
      schengen_status: 'Expired',
      company_info: 'XYZ Marketing Co.',
      passport_start_date: '2019-03-15',
      passport_end_date: '2029-03-15',
      visa_end_date: '2023-12-31',
      passport_jpg_url: 'https://example.com/passports/jane_smith.jpg',
      backup_1: 'Medical Info',
      backup_2: 'Emergency Contact',
  },
];